// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Config } from "./tables/Config.sol";
import { Rounds, RoundsData } from "./tables/Rounds.sol";
import { Teams, TeamsData } from "./tables/Teams.sol";
import { Bets, BetsData } from "./tables/Bets.sol";
