name: 'Lint PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          auth: ${{ secrets.PAT }}
          token: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.PAT }}