name: System tests

on: ["push"]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Install
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: Test
        run: yarn test:systems
