// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBetSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBetSystem {
  function placeBet(bytes32 _roundId, uint8 _teamId, uint256 _amount) external payable;

  function winnerWithdraw(bytes32 _roundId, uint8 _teamId) external;

  function refundWithdraw(bytes32 _roundId, uint8 _teamId) external;
}
