// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRoundSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRoundSystem {
  function createRound(
    uint256 _betPeriod,
    address[] memory _playerAddresses,
    string[] memory _names,
    uint8[] memory _teamIds,
    string memory _title
  ) external;

  function resolution(bytes32 _roundId, bytes32 matchEntity) external;
}
