// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RoundsData, TeamsData, BetsData } from "./../index.sol";

/**
 * @title IViewSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IViewSystem {
  function getConfigId() external view returns (bytes32);

  function getRound(bytes32 _roundId) external view returns (RoundsData memory);

  function getTeams(bytes32 _roundId, uint8 _teamId) external view returns (TeamsData memory);

  function getBets(bytes32 _roundId, uint8 _teamId, address _betterAddress) external view returns (BetsData memory);
}
